git_fixer_remove:
  - git_fixer2_MODIFIED*.py
  - intro_MODIFIED_*.md
  - _MODIFIED_*.gitignore
  - requirements_MODIFIED_*.txt
git_fixer_ignore:
  - config_git_fixer.yml
  - diff*.diff
  - class_*_MODIFIED*.ipynb
  - tracked_files*.txt
  - mod*.txt
  - assignments/*
  - "*_MODIFIED_*"
